"""added column for garbage quantity for BinPickupAssignment

Revision ID: 71a10a9c3500
Revises: 945ce30879c7
Create Date: 2025-10-07 00:36:02.098624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a10a9c3500'
down_revision: Union[str, Sequence[str], None] = '945ce30879c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_pickup_assignments', sa.Column('garbage_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bin_pickup_assignments', 'garbage_quantity')
    # ### end Alembic commands ###
